From clouden90/1d_mom6_cobalt:base

SHELL ["/bin/bash","-c"]

USER root

RUN apt update; apt install -y wget

USER builder

COPY --chown=builder:builder . /opt/MOM6_OBGC_examples

WORKDIR /opt

RUN wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/1d_datasets.tar.gz && tar -zxvf 1d_datasets.tar.gz && rm -rf 1d_datasets.tar.gz 

WORKDIR /opt/MOM6_OBGC_examples/builds

RUN /opt/MOM6_OBGC_examples/builds/linux-build.bash -m docker -p linux-gnu -t prod -f mom6sis2

WORKDIR /opt/MOM6_OBGC_examples/exps

RUN ln -fs /opt/datasets ./

WORKDIR /opt/MOM6_OBGC_examples/exps/OM4.single_column.COBALT.p4

RUN mpirun -np 1 /opt/MOM6_OBGC_examples/builds/build/docker-linux-gnu/ocean_ice/prod/MOM6SIS2
