# This is a basic workflow to help you get started with Actions

name: NWA12_RT

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events as well as specific label
  pull_request:
    branches: [ "dev/cefi" ]
    types: [ labeled ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "NWA12_RT_run"
  NWA12_RT_run:
    # run RT only when label 'NWA12_RT_gaea_c5' is on
    if: ${{ github.event.label.name == 'NWA12_RT_gaea_c5' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    env:
      MY_SECRET_KEY: ${{ secrets.CEFI_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run create_run_xml_from_template.bash 
      - name: create and run FRE xml
        run: |
          pwd
          cd ci
          #bash create_run_xml_from_template.bash 

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: success() && contains(github.event.label.name, 'NWA12_RT_gaea_c5')
        with:
          labels: pass_NWA12_RT
